package Activity1;

public class Pagulayan {
	public static void main (String[]args) {
		
        System.out.println("Full Name: Norielle Stacey E. Pagulayan");
    	System.out.println("Age: 19 years old");
    	System.out.println("Course and Year Level: BS Information Technology - 2nd Year");
    	System.out.println("School: University of Makati");
    	System.out.println("Hobbies: Listening to Music, Walking, Doing Makeup, and Dancing.");
    	System.out.println("Favorite Programming Language or Technology: Java ");
    	System.out.println("Reason why you want to learn Java: I want to learn Java because " +
    	                       "of its widespread use in enterprise applications, Android development, " +
    	                       "and its object-oriented approach which helps build a strong foundation " +
    	                       "for software materials. Additionally, Java's platform independence " +
    	                       "and robust ecosystem make it an essential skill for any developer.");
    	}
   
}
